#ifndef BODY_TRACK_CONSTANTS_H
#define BODY_TRACK_CONSTANTS_H

#include <k4abt.hpp>

// List of the parent joint ID of every child joint ID.
// For the root (pelvis), the parent is the joint itself.
const k4abt_joint_id_t JOINT_PARENTS[K4ABT_JOINT_COUNT] = {
    K4ABT_JOINT_PELVIS,
    K4ABT_JOINT_PELVIS,
    K4ABT_JOINT_SPINE_NAVEL,
    K4ABT_JOINT_SPINE_CHEST,
    K4ABT_JOINT_SPINE_CHEST,
    K4ABT_JOINT_CLAVICLE_LEFT,
    K4ABT_JOINT_SHOULDER_LEFT,
    K4ABT_JOINT_ELBOW_LEFT,
    K4ABT_JOINT_WRIST_LEFT,
    K4ABT_JOINT_HAND_LEFT,
    K4ABT_JOINT_WRIST_LEFT,
    K4ABT_JOINT_SPINE_CHEST,
    K4ABT_JOINT_CLAVICLE_RIGHT,
    K4ABT_JOINT_SHOULDER_RIGHT,
    K4ABT_JOINT_ELBOW_RIGHT,
    K4ABT_JOINT_WRIST_RIGHT,
    K4ABT_JOINT_HAND_RIGHT,
    K4ABT_JOINT_WRIST_RIGHT,
    K4ABT_JOINT_PELVIS,
    K4ABT_JOINT_HIP_LEFT,
    K4ABT_JOINT_KNEE_LEFT,
    K4ABT_JOINT_ANKLE_LEFT,
    K4ABT_JOINT_PELVIS,
    K4ABT_JOINT_HIP_RIGHT,
    K4ABT_JOINT_KNEE_RIGHT,
    K4ABT_JOINT_ANKLE_RIGHT,
    K4ABT_JOINT_NECK,
    K4ABT_JOINT_HEAD,
    K4ABT_JOINT_HEAD,
    K4ABT_JOINT_HEAD,
    K4ABT_JOINT_HEAD,
    K4ABT_JOINT_HEAD
};
#endif
